name: CI

env:
  TERM: screen-256color

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]
    tags:
      - "v*"

jobs:

  # Runs all steps on the VM
  linter:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile && pip-sync

      - name: isort
        run: |
          isort . --check-only --profile black
      - name: Black
        run: |
          black . --check
      - name: Flake8
        run: |
          flake8 .
